### ISSUE TITLE
meet some fails

### ISSUE THREAD

**Issue by jcluo1994** [VeronicaToro/image2data#1]
hello,this message from a studetn who from china.thank you for your contributor.but when i run this code ,there are some fails,NTEL MKL ERROR:  mkl_intel_thread.dll.
Intel MKL FATAL ERROR: Cannot load mkl_intel_thread.dll.  
if you know how to resolve this question,please tell me.thanks sincerely.

**Comment by VeronicaToro** [comment]
Hi @yichanshiwoa!
Sorry for the late reply, I didn't see this message before. 
Are you running it in Windows? I haven't tried this on Windows, so I'm afraid I cannot help you there.  But, maybe this other thread may be useful: https://github.com/ContinuumIO/anaconda-issues/issues/10213

**Comment by jcluo1994** [comment]
thank you for reply,i have solved this mistake with your help.
